import {useQuery} from '@tanstack/react-query';
import {ArrowRight,Briefcase,ExternalLink,GraduationCap,Mail,MapPin,Phone} from 'lucide-react';
import {Link,useParams} from 'react-router-dom';
import {api} from '../api/client';
import type {Profile} from '../types';

const numberFormatter=new Intl.NumberFormat('fa-IR');
export function ProfilePage(){const {id}=useParams();const q=useQuery({queryKey:['profile',id],queryFn:({signal})=>api.get<Profile>(`/profiles/${id}`,signal)});if(q.isLoading)return <div className="page state">در حال دریافت پروفایل…</div>;if(q.isError||!q.data)return <div className="page state"><h2>دریافت پروفایل امکان‌پذیر نیست</h2><Link to="/search">بازگشت به جست‌وجو</Link></div>;const p=q.data;return <div className="page detail"><Link className="back" to="/search"><ArrowRight/>بازگشت به نتایج</Link><section className="profile-hero"><div className="avatar large" dir="ltr">{p.full_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><div className="eyebrow">پروفایل حرفه‌ای</div><h1 dir="auto">{p.full_name}</h1><p dir="auto">{p.current_job_title} {p.current_company_name&&`در ${p.current_company_name}`}</p><span dir="auto"><MapPin/>{p.location.country||'موقعیت مکانی ثبت نشده'} {p.inferred_years_experience!=null&&`· ${numberFormatter.format(p.inferred_years_experience)} سال سابقه`}</span></div>{p.linkedin_url&&<a className="linkedin" href={p.linkedin_url} target="_blank" rel="noreferrer">لینکدین <ExternalLink/></a>}</section><div className="detail-grid"><div><Panel title="درباره"><p className="summary" dir="auto">{p.summary||'خلاصهٔ حرفه‌ای برای این پروفایل ثبت نشده است.'}</p><div className="chips" dir="auto">{p.skills.map(s=><span key={s}>{s}</span>)}</div></Panel><Panel title="سوابق شغلی" icon={<Briefcase/>}><div className="timeline">{p.experiences.map(x=><article key={x.id}><i/><h3 dir="auto">{x.title}</h3><strong dir="auto">{x.company_name}</strong><small>{formatDate(x.start_date)} — {x.end_date?formatDate(x.end_date):'اکنون'}</small>{x.summary&&<p dir="auto">{x.summary}</p>}</article>)}</div></Panel><Panel title="سوابق تحصیلی" icon={<GraduationCap/>}>{p.educations.map(x=><article className="education" key={x.id}><h3 dir="auto">{x.school_name}</h3><p dir="auto">{[...x.degrees,...x.majors].join(' · ')}</p></article>)}</Panel></div><aside><Panel title="اطلاعات تماس"><Contact icon={<Mail/>} label="ایمیل" value={p.primary_email}/><Contact icon={<Phone/>} label="تلفن همراه" value={p.mobile_phone}/></Panel><Panel title="در یک نگاه"><dl><div><dt>صنعت</dt><dd dir="auto">{(p as unknown as {industry?:string}).industry||'—'}</dd></div><div><dt>سابقه</dt><dd>{p.inferred_years_experience!=null?`${numberFormatter.format(p.inferred_years_experience)} سال`:'—'}</dd></div><div><dt>مهارت‌ها</dt><dd>{numberFormatter.format(p.skills.length)}</dd></div></dl></Panel></aside></div></div>}
const formatDate=(v?:string)=>v?new Intl.DateTimeFormat('fa-IR-u-ca-gregory',{year:'numeric',month:'short'}).format(new Date(v)):'—';
function Panel({title,icon,children}:{title:string;icon?:React.ReactNode;children:React.ReactNode}){return <section className="panel"><h2>{icon}{title}</h2>{children}</section>}
function Contact({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="contact">{icon}<div><small>{label}</small><span dir="auto">{value||'ثبت نشده'}</span></div></div>}
