import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="Profile", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("linkedin_id", models.CharField(blank=True, db_index=True, max_length=160, null=True, unique=True)), ("linkedin_url", models.URLField(blank=True, max_length=500, null=True, unique=True)), ("full_name", models.CharField(db_index=True, max_length=300)), ("first_name", models.CharField(blank=True, max_length=150)), ("last_name", models.CharField(blank=True, max_length=150)), ("gender", models.CharField(blank=True, max_length=40)), ("industry", models.CharField(blank=True, db_index=True, max_length=250)), ("summary", models.TextField(blank=True)), ("current_job_title", models.CharField(blank=True, db_index=True, max_length=300)), ("current_company_name", models.CharField(blank=True, max_length=300)), ("location_name", models.CharField(blank=True, max_length=300)), ("location_country", models.CharField(blank=True, db_index=True, max_length=150)), ("location_region", models.CharField(blank=True, max_length=150)), ("location_locality", models.CharField(blank=True, max_length=150)), ("inferred_years_experience", models.FloatField(blank=True, db_index=True, null=True)), ("primary_email", models.EmailField(blank=True, max_length=254)), ("mobile_phone", models.CharField(blank=True, max_length=80)), ("emails_json", models.JSONField(blank=True, default=list)), ("phone_numbers_json", models.JSONField(blank=True, default=list)), ("extras", models.JSONField(blank=True, default=dict)), ("raw_payload", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name="Skill", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=160)), ("normalized_name", models.CharField(db_index=True, max_length=160, unique=True))], options={"ordering": ["normalized_name"]}),
        migrations.CreateModel(name="Experience", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("company_name", models.CharField(blank=True, max_length=300)), ("company_industry", models.CharField(blank=True, max_length=250)), ("title", models.CharField(blank=True, max_length=300)), ("role", models.CharField(blank=True, max_length=200)), ("sub_role", models.CharField(blank=True, max_length=200)), ("start_date", models.DateField(blank=True, null=True)), ("end_date", models.DateField(blank=True, null=True)), ("is_primary", models.BooleanField(default=False)), ("summary", models.TextField(blank=True)), ("location_names", models.JSONField(blank=True, default=list)), ("raw_payload", models.JSONField(blank=True, default=dict)), ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="experiences", to="profiles.profile"))], options={"ordering": ["-is_primary", "-start_date"]}),
        migrations.CreateModel(name="Education", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("school_name", models.CharField(blank=True, max_length=300)), ("degrees", models.JSONField(blank=True, default=list)), ("majors", models.JSONField(blank=True, default=list)), ("minors", models.JSONField(blank=True, default=list)), ("start_date", models.DateField(blank=True, null=True)), ("end_date", models.DateField(blank=True, null=True)), ("gpa", models.CharField(blank=True, max_length=40)), ("summary", models.TextField(blank=True)), ("raw_payload", models.JSONField(blank=True, default=dict)), ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="educations", to="profiles.profile"))], options={"ordering": ["-end_date"]}),
        migrations.CreateModel(name="ProfileSkill", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="profiles.profile")), ("skill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="profiles.skill"))]),
        migrations.AddField(model_name="profile", name="skills", field=models.ManyToManyField(related_name="profiles", through="profiles.ProfileSkill", to="profiles.skill")),
        migrations.AddConstraint(model_name="profileskill", constraint=models.UniqueConstraint(fields=("profile", "skill"), name="unique_profile_skill")),
    ]

